# Generated by Django 4.2.4 on 2024-02-10 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("date", models.DateField()),
                ("number_of_likes", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="CommentAnswerLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_answer_like",
                        to="posts.commentanswer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_answer_like",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Comment_like",
            new_name="CommentLike",
        ),
        migrations.RenameModel(
            old_name="Post_like",
            new_name="PostLike",
        ),
        migrations.AddField(
            model_name="comment",
            name="number_of_likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="number_of_likes",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Comment_answer",
        ),
        migrations.AddField(
            model_name="commentanswer",
            name="comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="posts.comment",
            ),
        ),
        migrations.AddField(
            model_name="commentanswer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_answers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
