# Generated by Django 4.2.4 on 2024-02-07 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="user.seller",
            ),
        ),
        migrations.AddField(
            model_name="favouriteprofuct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourite_products",
                to="market.product",
            ),
        ),
        migrations.AddField(
            model_name="favouriteprofuct",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourited_by_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
