# Generated by Django 4.2.4 on 2024-04-03 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=500)),
                ("postal_code", models.CharField(max_length=100)),
                ("phonenumber", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=200)),
                ("accepted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Moderator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="city",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="phonenumber",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="postal_code",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Seller",
        ),
    ]
