# Generated by Django 4.2.4 on 2024-05-28 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_organization_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=500)),
                ("postal_code", models.CharField(max_length=100)),
                ("type_organization", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("INN", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=200)),
                ("accepted", models.BooleanField(default=False)),
                ("website_link", models.CharField(max_length=200)),
                ("representative_organizations", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=200)),
                ("goals_description", models.TextField()),
                ("logo", models.ImageField(upload_to="organization_logo/")),
                (
                    "instagram",
                    models.CharField(default=None, max_length=400, null=True),
                ),
                ("facebook", models.CharField(default=None, max_length=400, null=True)),
                ("youtube", models.CharField(default=None, max_length=400, null=True)),
                ("telegram", models.CharField(default=None, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationRedactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passport_photo", models.ImageField(upload_to="redactors_passport/")),
                ("application_statement", models.TextField()),
                ("city", models.CharField(max_length=500)),
                ("country", models.CharField(max_length=400)),
                ("photo", models.ImageField(upload_to="redactors/")),
                ("description", models.TextField()),
                (
                    "instagram",
                    models.CharField(default=None, max_length=400, null=True),
                ),
                ("facebook", models.CharField(default=None, max_length=400, null=True)),
                ("youtube", models.CharField(default=None, max_length=400, null=True)),
                ("telegram", models.CharField(default=None, max_length=400, null=True)),
                ("accepted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationVolonteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passport_photo", models.ImageField(upload_to="redactors_passport/")),
                ("volonteer_type", models.CharField(max_length=300)),
                ("city", models.CharField(max_length=500)),
                ("country", models.CharField(max_length=400)),
                ("photo", models.ImageField(upload_to="redactors/")),
                ("description", models.TextField()),
                (
                    "instagram",
                    models.CharField(default=None, max_length=400, null=True),
                ),
                ("facebook", models.CharField(default=None, max_length=400, null=True)),
                ("youtube", models.CharField(default=None, max_length=400, null=True)),
                ("telegram", models.CharField(default=None, max_length=400, null=True)),
                ("accepted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="FavouriteOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavouriteVolonteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Redactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passport_photo", models.ImageField(upload_to="redactors_passport/")),
                ("application_statement", models.TextField()),
                ("city", models.CharField(max_length=500)),
                ("country", models.CharField(max_length=400)),
                ("photo", models.ImageField(upload_to="redactors/")),
                ("description", models.TextField()),
                (
                    "instagram",
                    models.CharField(default=None, max_length=400, null=True),
                ),
                ("facebook", models.CharField(default=None, max_length=400, null=True)),
                ("youtube", models.CharField(default=None, max_length=400, null=True)),
                ("telegram", models.CharField(default=None, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegistrationDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="registration_documents/")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_registration_documents",
                        to="user.applicationorganization",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Application",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="email",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="phonenumber",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_judical",
        ),
        migrations.RemoveField(
            model_name="user",
            name="middle_name",
        ),
        migrations.RemoveField(
            model_name="volonteer",
            name="uen_coins",
        ),
        migrations.AddField(
            model_name="organization",
            name="facebook",
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to="organizations/"),
        ),
        migrations.AddField(
            model_name="organization",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to="organizations/"),
        ),
        migrations.AddField(
            model_name="organization",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to="organizations/"),
        ),
        migrations.AddField(
            model_name="organization",
            name="image4",
            field=models.ImageField(blank=True, null=True, upload_to="organizations/"),
        ),
        migrations.AddField(
            model_name="organization",
            name="image5",
            field=models.ImageField(blank=True, null=True, upload_to="organizations/"),
        ),
        migrations.AddField(
            model_name="organization",
            name="image6",
            field=models.ImageField(blank=True, null=True, upload_to="organizations/"),
        ),
        migrations.AddField(
            model_name="organization",
            name="image7",
            field=models.ImageField(blank=True, null=True, upload_to="organizations/"),
        ),
        migrations.AddField(
            model_name="organization",
            name="image8",
            field=models.ImageField(blank=True, null=True, upload_to="organizations/"),
        ),
        migrations.AddField(
            model_name="organization",
            name="image9",
            field=models.ImageField(blank=True, null=True, upload_to="organizations/"),
        ),
        migrations.AddField(
            model_name="organization",
            name="instagram",
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="telegram",
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="youtube",
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="volonteer",
            name="city",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="volonteer",
            name="country",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="volonteer",
            name="description",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="volonteer",
            name="facebook",
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="volonteer",
            name="instagram",
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="volonteer",
            name="passport_photo",
            field=models.ImageField(default=None, upload_to="volonteers_passport/"),
        ),
        migrations.AddField(
            model_name="volonteer",
            name="photo",
            field=models.ImageField(default=None, upload_to="volonteers/"),
        ),
        migrations.AddField(
            model_name="volonteer",
            name="telegram",
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="volonteer",
            name="volonteer_type",
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name="volonteer",
            name="youtube",
            field=models.CharField(default=None, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="registrationdocuments",
            name="organization",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_registration_documents",
                to="user.organization",
            ),
        ),
        migrations.AddField(
            model_name="redactor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redactor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="favouritevolonteer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourite_vol_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="favouritevolonteer",
            name="volonteer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourite_vol",
                to="user.volonteer",
            ),
        ),
        migrations.AddField(
            model_name="favouriteorganization",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourite_org",
                to="user.organization",
            ),
        ),
        migrations.AddField(
            model_name="favouriteorganization",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favourite_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="applicationvolonteer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_application_vol",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="applicationredactor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_application_red",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
