# Generated by Django 4.2.4 on 2024-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_applicationorganization_applicationredactor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
