# Generated by Django 4.2.4 on 2024-05-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_birthday_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volonteer",
            name="city",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="volonteer",
            name="country",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="volonteer",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="volonteer",
            name="passport_photo",
            field=models.ImageField(
                default=None, null=True, upload_to="volonteers_passport/"
            ),
        ),
        migrations.AlterField(
            model_name="volonteer",
            name="photo",
            field=models.ImageField(default=None, null=True, upload_to="volonteers/"),
        ),
        migrations.AlterField(
            model_name="volonteer",
            name="volonteer_type",
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
