# Generated by Django 4.2.4 on 2024-05-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_volonteer_city_alter_volonteer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logo_org/'),
        ),
    ]
